update scan yml

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -1,9 +1,9 @@
 name: Coverity Scan
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "CWE-918" ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ "CWE-918" ]
   workflow_dispatch:
     inputs:
       languages:
@@ -38,15 +38,44 @@ jobs:
           tar -xvzf coverity_tool.tgz -C coverity_tool --strip-components=1
           export PATH=$PWD/coverity_tool/bin:$PATH
           echo "Coverity Tool installed successfully"
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y \
+            build-essential \
+            cmake \
+            git \
+            libx11-dev \
+            libxrandr-dev \
+            libudev-dev \
+            libgl1-mesa-dev \
+            libflac-dev \
+            libogg-dev \
+            libvorbis-dev \
+            libopenal-dev \
+            libfreetype6-dev \
+            libxi-dev \
+            libxcursor-dev \
+            libxinerama-dev \
+            libxrandr-dev \
+            libxrender-dev \
+            libxfixes-dev \
+            libxext-dev \
+            libcurl4-openssl-dev
       - name: Build with Coverity
         run: |
-          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
-          sudo apt-get update
-          sudo apt-get build-dep libsfml-dev
-          sudo apt-get install libxi-dev
           mkdir build
-          cmake -B build
-          coverity_tool/bin/cov-build --dir cov-int cmake --build build || echo 'Errors on Coverity build'
+          cd build
+          cmake .. \
+            -DCMAKE_BUILD_TYPE=Debug \
+            -DSFML_BUILD_EXAMPLES=ON \
+            -DSFML_BUILD_DOC=OFF \
+            -DSFML_BUILD_NETWORK=ON \
+            -DSFML_BUILD_AUDIO=ON \
+            -DSFML_BUILD_GRAPHICS=ON \
+            -DSFML_BUILD_WINDOW=ON \
+            -DSFML_BUILD_SYSTEM=ON
+          coverity_tool/bin/cov-build --dir cov-int cmake --build . || echo 'Errors on Coverity build'
       - name: Compress with bzip2
         run: |
           tar cjvf myproject.tar.bz2 cov-int
