final changes

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -40,59 +40,10 @@ jobs:
           echo "COVERITY_PATH=$(pwd)/coverity_tool/bin" >> $GITHUB_ENV
           echo "PATH=$(pwd)/coverity_tool/bin:$PATH" >> $GITHUB_ENV
           echo "Coverity Tool installed successfully"
-      - name: Install Dependencies
+      - name: Build with Docker and Coverity
         run: |
-          sudo apt-get update && sudo apt-get install -y \
-            build-essential \
-            cmake \
-            git \
-            pkg-config \
-            libx11-dev \
-            libxrandr-dev \
-            libudev-dev \
-            libgl1-mesa-dev \
-            libflac-dev \
-            libogg-dev \
-            libvorbis-dev \
-            libopenal-dev \
-            libfreetype6-dev \
-            libjpeg-dev \
-            libpng-dev \
-            libssl-dev \
-            libmongoc-dev \
-            libbson-dev \
-            libmysqlclient-dev \
-            libxcursor-dev \
-            libxi-dev
-      - name: Build with Coverity
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            build-essential \
-            cmake \
-            git \
-            pkg-config \
-            libx11-dev \
-            libxrandr-dev \
-            libudev-dev \
-            libgl1-mesa-dev \
-            libflac-dev \
-            libogg-dev \
-            libvorbis-dev \
-            libopenal-dev \
-            libfreetype6-dev \
-            libxi-dev \
-            libxcursor-dev \
-            libxinerama-dev \
-            libxrandr-dev \
-            libxrender-dev \
-            libxfixes-dev \
-            libxext-dev \
-            libcurl4-openssl-dev \
-            libmongoc-dev \
-            libbson-dev
-
-          cmake -B build \
+          docker build -t sfml-build .
+          $COVERITY_PATH/cov-build --dir cov-int docker run --rm sfml-build cmake -B build \
             -DCMAKE_BUILD_TYPE=Debug \
             -DSFML_BUILD_EXAMPLES=ON \
             -DSFML_BUILD_DOC=OFF \
@@ -103,8 +54,7 @@ jobs:
             -DCMAKE_CXX_FLAGS="-fPIC" \
             -DCMAKE_C_FLAGS="-fPIC" \
             -DBUILD_SHARED_LIBS=ON
-
-          $COVERITY_PATH/cov-build --dir cov-int cmake --build build || echo 'Errors on Coverity build'
+          $COVERITY_PATH/cov-build --dir cov-int docker run --rm sfml-build cmake --build build || echo 'Errors on Coverity build'
 
       - name: Compress with bzip2
         run: |
